// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetTransactionByID(arg1:string):Promise<models.Transaction>;

export function GetTransactions(arg1:models.TransactionFilters):Promise<Array<models.Transaction>>;

export function SaveTransaction(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function SoftDeleteTransaction(arg1:string):Promise<string>;
