// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddCategory(arg1:string,arg2:number):Promise<void>;

export function AddRecurringSchedule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:boolean):Promise<void>;

export function AddSetting(arg1:string,arg2:string):Promise<void>;

export function DeleteBudget(arg1:string,arg2:string):Promise<void>;

export function GenerateRecurringTransactions(arg1:string):Promise<number>;

export function GetBudgetSummaries(arg1:string):Promise<Array<models.BudgetSummary>>;

export function GetCategories():Promise<Array<models.Category>>;

export function GetCurrencyCode():Promise<string>;

export function GetFinancialMetrics(arg1:string,arg2:string):Promise<models.FinancialMetrics>;

export function GetNotificationsEnabled():Promise<boolean>;

export function GetRecurringSchedules():Promise<Array<models.RecurringSchedule>>;

export function GetSettings(arg1:string):Promise<Array<models.SettingItem>>;

export function GetSpendingReport(arg1:string,arg2:string):Promise<models.SpendingReport>;

export function GetTransactionByID(arg1:string):Promise<models.Transaction>;

export function GetTransactions(arg1:models.TransactionFilters):Promise<Array<models.Transaction>>;

export function ImportStatementRows(arg1:Array<models.StatementEntry>,arg2:models.StatementImportOptions):Promise<models.StatementImportResult>;

export function InactivateSetting(arg1:string,arg2:string):Promise<void>;

export function InspectStatementCSV(arg1:string,arg2:string,arg3:boolean):Promise<models.StatementInspection>;

export function PreviewStatementCSV(arg1:string,arg2:models.StatementParseOptions):Promise<models.StatementPreview>;

export function RestoreTransaction(arg1:string):Promise<string>;

export function SaveBudget(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveInstallmentTransactions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:number):Promise<string>;

export function SaveTransaction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:boolean):Promise<string>;

export function SetCurrencyCode(arg1:string):Promise<void>;

export function SetNotificationsEnabled(arg1:boolean):Promise<void>;

export function SetTransactionReconciled(arg1:string,arg2:boolean):Promise<void>;

export function SoftDeleteCategory(arg1:string):Promise<void>;

export function SoftDeleteTransaction(arg1:string):Promise<string>;

export function StopRecurringSchedule(arg1:string):Promise<void>;

export function UpdateCategory(arg1:string,arg2:string,arg3:number):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateTransaction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:boolean):Promise<string>;
