// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTransactionByID(arg1) {
  return window['go']['main']['App']['GetTransactionByID'](arg1);
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function SaveTransaction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTransaction'](arg1, arg2, arg3, arg4);
}

export function SoftDeleteTransaction(arg1) {
  return window['go']['main']['App']['SoftDeleteTransaction'](arg1);
}
