// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1, arg2) {
  return window['go']['main']['App']['AddCategory'](arg1, arg2);
}

export function AddSetting(arg1, arg2) {
  return window['go']['main']['App']['AddSetting'](arg1, arg2);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetSettings(arg1) {
  return window['go']['main']['App']['GetSettings'](arg1);
}

export function GetTransactionByID(arg1) {
  return window['go']['main']['App']['GetTransactionByID'](arg1);
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function InactivateSetting(arg1, arg2) {
  return window['go']['main']['App']['InactivateSetting'](arg1, arg2);
}

export function SaveTransaction(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SaveTransaction'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SoftDeleteCategory(arg1) {
  return window['go']['main']['App']['SoftDeleteCategory'](arg1);
}

export function SoftDeleteTransaction(arg1) {
  return window['go']['main']['App']['SoftDeleteTransaction'](arg1);
}

export function UpdateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2, arg3);
}

export function UpdateSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2, arg3);
}
